yolov26_detector:
  ros__parameters:
    weights: "/home/highlevel/roboboat_usv/src/asv_perception/yolov26_ros/weights/best.pt"
    input_topic: "/zed/zed_node/rgb/color/rect/image"
    output_topic_image: "/yolov8/annotated_image/center"
    output_topic_detections: "/yolov8/detections/center"

    conf: 0.50
    iou: 0.45
    imgsz: 640
    device: "cuda:0"   # or "cpu"
    max_det: 300
