<package format="3">
  <name>vision_cpp</name>
  <version>0.0.0</version>
  <description>Voxel grid filter using PCL in ROS2</description>
  <maintainer email="your_email@domain.com">Your Name</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>pcl_conversions</depend>
  <depend>pcl_ros</depend>
  <depend>fau_msgs</depend>
  <depend>lidar_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>OpenCV</depend>
  <depend>image_transport</depend>
  <depend>yolov26_msgs</depend>
  <depend>vizualization_msgs</depend>


  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>

