from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    asv = LaunchConfiguration("asv")
    velD = LaunchConfiguration("velD")
    lookahead_m = LaunchConfiguration("lookahead_m")

    return LaunchDescription([
        DeclareLaunchArgument(
            "asv",
            default_value="asv",
            description="ASV robot name / namespace",
        ),
        DeclareLaunchArgument(
            "velD",
            default_value="0.8",
            description="Desired speed for PID_HS/APF waypoint bridge [m/s]",
        ),
        DeclareLaunchArgument(
            "lookahead_m",
            default_value="4.0",
            description="Lookahead distance along APF desired path [m]",
        ),

        # ------------------------------------------------------------
        # APF CONTROLLER USED AS PATH GENERATOR ONLY
        # Flow:
        #   apf_controller_diff -> /<asv>/viz/apf_desired_path
        #   apf_controller_diff -> /<asv>/control_effort_apf_unused  (ignored)
        # ------------------------------------------------------------
        Node(
            package="apf_grid_controller",
            executable="apf_controller_diff",
            name="apf_controller_diff",
            parameters=[
                {
                    "asv": asv,
                    "wamv": asv,
                    "use_sim_time": False,

                    "pose_topic": "vehicle_pose",
                    "odom_topic": "p3d_wamv_ned",
                    "map_topic": "map/local_occupancy_2",
                    "goal_topic": "nav/goal",

                    # IMPORTANT: PID_HS will publish the real /control_effort.
                    # APF control output is redirected so it does not fight PID.
                    "control_effort_topic": "control_effort_apf_unused",

                    # Occupancy-grid obstacle extraction
                    "occ_threshold": 80,
                    "treat_unknown_as_occupied": False,
                    "window_radius_m": 30.0,
                    "max_obstacles": 1000,
                    "downsample_stride": 2,

                    # APF tuning
                    "ka": 40.0,
                    "kr": 3.0,
                    "rho": 5.0,
                    "r_usv": 0.5,
                    "c_safe": 0.9,
                    "Fcap": 150.0,

                    # Wall-following / local-minimum escape
                    "d_slide": 11.0,
                    "w_max": 1.2,
                    "k_wall": 11.0,
                    "K_yaw_apf": 100.0,

                    # Force limits kept for APF internal rollout/path generation
                    "F_max": 50.0,
                    "Mz_max": 45.0,

                    # Damping
                    "Kd_diag": [35.0, 0.0, 10.0],

                    # Timing
                    "dt": 0.1,

                    # RViz APF path generated by this controller
                    "apf_path_num_points": 80,
                    "apf_path_ds": 0.6,
                    "apf_path_max_yaw_rate": 0.6,

                    # RViz topics
                    "actual_path_topic": "viz/apf_actual_path",
                    "desired_path_topic": "viz/apf_desired_path",
                    "goal_marker_topic": "viz/apf_goal_marker",
                    "vehicle_pose_viz_topic": "viz/apf_vehicle_pose",
                    "vehicle_marker_topic": "viz/apf_vehicle_marker",
                    "vehicle_marker_length_m": 2.0,
                    "vehicle_marker_width_m": 0.35,
                    "path_max_len": 2000,
                    "viz_frame_id": "map",
                }
            ],
            output="screen",
        ),
        Node(
            package="apf_grid_controller",
            executable="fixed_points",
            name="fixed_points",
            output="screen",
            parameters=[{
                "asv": asv,
                "frame_id": "map",
                "rate_hz": 2.0,

                "waypoint0_x": -20.0,
                "waypoint0_y": 50.0,

                "waypoint1_x": -20.0,
                "waypoint1_y": 48.5,

                "waypoint2_x": -19.7,
                "waypoint2_y": 37.8,

                "waypoint3_x": -19.3,
                "waypoint3_y": 33.7,

                "waypoint4_x": -18.3,
                "waypoint4_y": 25.7,

                "waypoint5_x": -17.7,
                "waypoint5_y": 21.8,

                "waypoint6_x": -16.8,
                "waypoint6_y": 8.0,

                "waypoint7_x": -16.5,
                "waypoint7_y": 6.0,


                "switch_radius_m": 2.0,

                "require_start_heading": False,
                "switch_heading_tolerance_deg": 25.0,
            }],
        ),



        # ------------------------------------------------------------
        # APF PATH -> PID/RL DESIRED-STATE BRIDGE
        # Flow:
        #   /<asv>/viz/apf_desired_path -> /<asv>/traj_desired_state
        # ------------------------------------------------------------
        Node(
            package="apf_grid_controller",
            executable="apf_planner",
            name="apf_planner",
            parameters=[
                {
                    "asv": asv,
                    "apf_path_topic": "viz/apf_desired_path",
                    "pose_topic": "vehicle_pose",
                    "desired_state_topic": "traj_desired_state",
                    "velD_topic": "velD",
                    "controller_topic": "controller",
                    "velD": velD,
                    "lookahead_m": lookahead_m,
                    "goal_acceptance_m": 0.8,
                    "dt": 0.1,
                    "publish_controller": True,
                    "controller_name": "HS",
                    "publish_markers": True,
                    "marker_topic": "viz/pid_apf_target",
                    "marker_frame_id": "map",
                }
            ],
            output="screen",
        ),

        # ------------------------------------------------------------
        # PID_HS CONTROLLER
        # Flow:
        #   /<asv>/traj_desired_state -> PID_HS -> /<asv>/control_effort
        # ------------------------------------------------------------
        Node(
            package="pid_hs",
            executable="pid_hs_node",
            name="pid_hs_node",
            output="screen",
            parameters=[
                # Speed -> physical surge force [N]
                {"kp_v": 100.0},
                {"ki_v": 10.0},
                {"kd_v": 0.0},

                # Heading -> physical yaw moment [N m]
                {"kp_psi": 30.0},
                {"ki_psi": 0.0},
                {"kd_psi": 0.0},

                {"dt": 0.1},

                # Same limits as Direct APF
                {"Tx_max": 50.0},
                {"Mz_max": 45.0},

                {"asv": asv},
                {"velD": velD},
            ],
        ),

        # ------------------------------------------------------------
        # PWM ALLOCATION FOR PID_HS CONTROL EFFORT
        # Flow:
        #   /<asv>/control_effort -> usv_allocation_diff -> /<asv>/motor_cmds
        # ------------------------------------------------------------
        Node(
            package="apf_grid_controller",
            executable="allocation_diff",
            name="allocation_diff_pid",
            parameters=[
                {
                    "asv": asv,
                    "B": 0.62,
                    "use_controller_gate": True,
                    "controller_name": "HS",
                    "publish_force_debug": True,
                }
            ],
            output="screen",
        ),
    ])
