from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    asv = LaunchConfiguration("asv")

    return LaunchDescription([
        DeclareLaunchArgument(
            "asv",
            default_value="asv",
            description="ASV robot name / namespace",
        ),

        # ------------------------------------------------------------
        # DIRECT APF CONTROLLER
        # Flow:
        #   apf_controller_diff -> /<asv>/control_effort
        #   allocation_diff     -> /<asv>/motor_cmds
        # ------------------------------------------------------------
        Node(
            package="apf_grid_controller",
            executable="allocation_diff",
            name="allocation_diff",
            parameters=[
                {
                    "asv": asv,
                    "wamv": asv,
                }
            ],
            output="screen",
        ),
        Node(
            package="apf_grid_controller",
            executable="fixed_points",
            name="fixed_points",
            output="screen",
            parameters=[{
                "asv": asv,
                "frame_id": "map",
                "rate_hz": 2.0,

                "waypoint0_x": -20.0,
                "waypoint0_y": 50.0,

                "waypoint1_x": -20.0,
                "waypoint1_y": 48.5,

                "waypoint2_x": -19.7,
                "waypoint2_y": 37.8,

                "waypoint3_x": -19.3,
                "waypoint3_y": 33.7,

                "waypoint4_x": -18.3,
                "waypoint4_y": 25.7,

                "waypoint5_x": -17.7,
                "waypoint5_y": 21.8,

                "waypoint6_x": -15.8,
                "waypoint6_y": 13.0,

                "waypoint7_x": -15.5,
                "waypoint7_y": 11.0,
                "switch_radius_m": 2.0,

                "require_start_heading": False,
                "switch_heading_tolerance_deg": 25.0,
            }],
        ),

        Node(
            package="apf_grid_controller",
            executable="apf_controller_diff",
            name="apf_controller_diff",
            parameters=[
                {
                    # Pass both because some of your nodes use `asv`, while
                    # apf_controller_diff internally reads `wamv`.
                    "asv": asv,
                    "wamv": asv,
                    "use_sim_time": False,

                    "pose_topic": "vehicle_pose",
                    "odom_topic": "p3d_wamv_ned",
                    "map_topic": "map/local_occupancy_2",
                    "goal_topic": "nav/goal",

                    # DIRECT APF: publish to the real control-effort topic.
                    "control_effort_topic": "control_effort",

                    # Occupancy-grid obstacle extraction
                    "occ_threshold": 80,
                    "treat_unknown_as_occupied": False,
                    "window_radius_m": 30.0,
                    "max_obstacles": 1000,
                    "downsample_stride": 2,

                    # APF tuning
                    "ka": 40.0,
                    "kr": 3.0,
                    "rho": 5.0,
                    "r_usv": 0.5,
                    "c_safe": 0.7,
                    "Fcap": 150.0,

                    # Wall-following / local-minimum escape
                    "d_slide": 11.0,
                    "w_max": 1.2,
                    "k_wall": 11.0,
                    "K_yaw_apf": 120.0,

                    # Force limits
                    "F_max": 50.0,
                    "Mz_max": 45.0,

                    # Damping
                    "Kd_diag": [35.0, 0.0, 5.0],

                    "use_lookahead_yaw": True,
                    "yaw_lookahead_m": 4.0,
                    "yaw_lookahead_blend": 0.7,
                    "yaw_lookahead_min_dist": 0.6,
                    "yaw_lookahead_min_field_strength": 0.30,

                    # Timing
                    "dt": 0.1,

                    # RViz APF path generated by this controller
                    "apf_path_num_points": 80,
                    "apf_path_ds": 0.6,
                    "apf_path_max_yaw_rate": 0.6,

                    # RViz topics
                    "actual_path_topic": "viz/apf_actual_path",
                    "desired_path_topic": "viz/apf_desired_path",
                    "goal_marker_topic": "viz/apf_goal_marker",
                    "vehicle_pose_viz_topic": "viz/apf_vehicle_pose",
                    "vehicle_marker_topic": "viz/apf_vehicle_marker",
                    "vehicle_marker_length_m": 2.0,
                    "vehicle_marker_width_m": 0.35,
                    "path_max_len": 2000,
                    "viz_frame_id": "map",
                }
            ],
            output="screen",
        ),
    ])
