from launch import LaunchDescription
from launch.actions import DeclareLaunchArgument
from launch.substitutions import LaunchConfiguration
from launch_ros.actions import Node


def generate_launch_description():
    asv = LaunchConfiguration("asv")
    lookahead_m = LaunchConfiguration("lookahead_m")
    model_path = LaunchConfiguration("model_path")
    vecnormalize_path = LaunchConfiguration("vecnormalize_path")

    return LaunchDescription([
        DeclareLaunchArgument(
            "asv",
            default_value="asv",
            description="ASV robot name / namespace",
        ),
        DeclareLaunchArgument(
            "lookahead_m",
            default_value="15.0",
            description="Lookahead distance along APF desired path [m]",
        ),
        DeclareLaunchArgument(
            "model_path",
            default_value="/home/highlevel/roboboat_usv/src/asv_control/rl_control/rl_control/ppo_roboboat.zip",
            description="Path to trained PPO .zip model",
        ),
        DeclareLaunchArgument(
            "vecnormalize_path",
            default_value="/home/highlevel/roboboat_usv/src/asv_control/rl_control/rl_control/vecnormalize_roboboat.pkl",
            description="Path to VecNormalize .pkl stats",
        ),

        # ------------------------------------------------------------
        # APF CONTROLLER USED AS PATH GENERATOR ONLY
        # Flow:
        #   apf_controller_diff -> /<asv>/viz/apf_desired_path
        #   apf_controller_diff -> /<asv>/control_effort_apf_unused  (ignored)
        # ------------------------------------------------------------
        Node(
            package="apf_grid_controller",
            executable="apf_controller_diff",
            name="apf_controller_diff",
            parameters=[
                {
                    "asv": asv,
                    "wamv": asv,
                    "use_sim_time": False,

                    "pose_topic": "vehicle_pose",
                    "odom_topic": "p3d_wamv_ned",
                    "map_topic": "map/local_occupancy_2",
                    "goal_topic": "nav/goal",

                    # IMPORTANT: RL publishes motor_cmds directly.
                    # APF control output is redirected so it does not command motors.
                    "control_effort_topic": "control_effort_apf_unused",

                    # Occupancy-grid obstacle extraction
                    "occ_threshold": 80,
                    "treat_unknown_as_occupied": False,
                    "window_radius_m": 30.0,
                    "max_obstacles": 1000,
                    "downsample_stride": 2,

                    # APF tuning
                    "ka": 40.0,
                    "kr": 3.0,
                    "rho": 5.0,
                    "r_usv": 0.5,
                    "c_safe": 0.9,
                    "Fcap": 150.0,

                    # Wall-following / local-minimum escape
                    "d_slide": 11.0,
                    "w_max": 1.2,
                    "k_wall": 11.0,
                    "K_yaw_apf": 100.0,

                    # Force limits kept for APF internal rollout/path generation
                    "F_max": 50.0,
                    "Mz_max": 45.0,

                    # Damping
                    "Kd_diag": [35.0, 0.0, 10.0],

                    # Timing
                    "dt": 0.1,

                    # RViz APF path generated by this controller
                    "apf_path_num_points": 80,
                    "apf_path_ds": 0.6,
                    "apf_path_max_yaw_rate": 0.6,

                    # RViz topics
                    "actual_path_topic": "viz/apf_actual_path",
                    "desired_path_topic": "viz/apf_desired_path",
                    "goal_marker_topic": "viz/apf_goal_marker",
                    "vehicle_pose_viz_topic": "viz/apf_vehicle_pose",
                    "vehicle_marker_topic": "viz/apf_vehicle_marker",
                    "vehicle_marker_length_m": 2.0,
                    "vehicle_marker_width_m": 0.35,
                    "path_max_len": 2000,
                    "viz_frame_id": "map",
                }
            ],
            output="screen",
        ),
        Node(
            package="apf_grid_controller",
            executable="fixed_points",
            name="fixed_points",
            output="screen",
            parameters=[{
                "asv": asv,
                "frame_id": "map",
                "rate_hz": 2.0,

                "start_x": -14.54661750793457,
                "start_y": 39.37781524658203,
                "start_theta": 0.23467254638671875,

                "goal_x": -12.0,
                "goal_y": 20.0,
                "goal_theta": 0.0,

                "start_pos_tolerance_m": 1.0,
                "start_heading_tolerance_deg": 25.0,
            }],
        ),

        # ------------------------------------------------------------
        # APF PATH -> PID/RL DESIRED-STATE BRIDGE
        # Flow:
        #   /<asv>/viz/apf_desired_path -> /<asv>/traj_desired_state
        # ------------------------------------------------------------
        Node(
            package="apf_grid_controller",
            executable="apf_planner",
            name="apf_planner",
            parameters=[
                {
                    "asv": asv,
                    "velD": 0.5,
                    "lookahead_m": lookahead_m,
                    "controller_name": "RL",

                    # RL fixed-waypoint mode
                    "waypoint_mode": "discrete",
                    "switch_radius_m": 1.0,
                    "target_replan_distance_m": 6.0,
                }
            ],
            output="screen",
        ),

        # ------------------------------------------------------------
        # RL CONTROLLER
        # Flow:
        #   /<asv>/traj_desired_state -> RL -> /<asv>/motor_cmds
        # No allocation node here.
        # ------------------------------------------------------------
        Node(
            package="rl_control",
            executable="rl_control_roboboat",
            name="rl_control_roboboat",
            parameters=[
                {
                    "asv": asv,
                    "model_path": model_path,
                    "vecnormalize_path": vecnormalize_path,
                    "use_vecnormalize": True,
                    "odom_twist_frame": "world_ned",
                    "use_controller_gate": True,
                    "controller_name": "RL",
                    "require_goal": True,
                    "motor_cmds_topic": "motor_cmds",
                    # RoboBoat PWM convention: +100% forward -> 1000 PWM.
                    "forward_pwm_decreases": True,
                }
            ],
            output="screen",
        ),
    ])
